// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lease } from "./Lease";
import type { Rule } from "./Rule";

export interface Client { id: number | null, ip: string, name: string, rules: Array<Rule>, leases: Array<Lease>, }