// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rule } from "./Rule";

export interface Lease { end_date_utc: number | null, end_date: string | null, rule: Rule, }