// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Rule { kind: RuleKind, domainlists: Array<number>, }

export enum RuleKind {
  ALLOW_HTTP_ACCESS = "allow_http_access",
  DENY_HTTP_ACCESS = "deny_http_access"
}

