name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test backend
        working-directory: ./server
        run: |
          rustup default nightly
          rustup component add clippy
          cargo clippy -p penguin -- --no-deps
          cargo test